### ISSUE TITLE
Flaky vanadium-go-rpc-stress target

### ISSUE THREAD

**Issue by hpucha** [vanadium/issues#1029]
Not sure if this is the issue, but this failure is a common pattern

11:16:45 tmpnode-rpc-stress-client-03: workers: 8, maxChunkCnt: 100, maxPayloadSize: 10000, duration: 1h0m0s
11:16:45 tmpnode-rpc-stress-client-03: F1225 19:16:40.089389    2085 client.go:76] Stream failed: EOF
11:16:45 tmpnode-rpc-stress-client-03: goroutine 50 [running]:

https://veyron.corp.google.com/jenkins/job/vanadium-go-rpc-stress/707/console
https://veyron.corp.google.com/jenkins/job/vanadium-go-rpc-stress/713/console
# 

Another one

05:17:18 tmpnode-rpc-stress-client-01: workers: 8, maxChunkCnt: 100, maxPayloadSize: 10000, duration: 1h0m0s
05:17:18 tmpnode-rpc-stress-client-01: F1227 13:17:12.701049    2099 client.go:57] Sum failed: EOF

https://veyron.corp.google.com/jenkins/job/vanadium-go-rpc-stress/714/console

**Comment by jhahn21** [comment]
This happens quite frequently. Any idea what is the issue here?
