### ISSUE TITLE
Failure in rpc stress test: SumStream: Bad protocol or type: failed to encode arg #-1: EOF

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#1034]
https://veyron.corp.google.com/jenkins/job/vanadium-go-rpc-stress/746/console

```
05:16:40 tmpnode-rpc-stress-client-04: [run] create tmpdir "./tmp_712B1A6CDB20ABFB"
05:16:40 tmpnode-rpc-stress-client-04: Warning: Permanently added '104.197.112.92' (ECDSA) to the list of known hosts.
05:16:40 tmpnode-rpc-stress-client-04: [run] copy files to node [/usr/local/google/home/veyron/workspace/vanadium-go-rpc-stress/root/release/go/bin/stress]
05:16:40 tmpnode-rpc-stress-client-04: Warning: Permanently added '104.197.112.92' (ECDSA) to the list of known hosts.
05:16:40 tmpnode-rpc-stress-client-04: [run] run cmdline [cd ./tmp_712B1A6CDB20ABFB ; ./stress stress -workers 8 -max-chunk-count 100 -max-payload-size 10000 -duration 1h0m0s -format json /tmpnode-rpc-stress-server-00:10000 /tmpnode-rpc-stress-server-01:10000 /tmpnode-rpc-stress-server-02:10000]
05:16:40 tmpnode-rpc-stress-client-04: Warning: Permanently added '104.197.112.92' (ECDSA) to the list of known hosts.
05:16:40 tmpnode-rpc-stress-client-04: starting stress test against 3 server(s) using 4 core(s)...
05:16:40 tmpnode-rpc-stress-client-04: workers: 8, maxChunkCnt: 100, maxPayloadSize: 10000, duration: 1h0m0s
05:16:40 tmpnode-rpc-stress-client-04: F0104 13:16:37.517884    2105 client.go:115] SendStream failed to send: stress:<rpc.Client>"/tmpnode-rpc-stress-server-01:10000".SumStream: Bad protocol or type: failed to encode arg #-1: EOF:
05:16:40 tmpnode-rpc-stress-client-04: goroutine 44 [running]:
05:16:40 tmpnode-rpc-stress-client-04: github.com/cosnicolaou/llog.stacks(0xc82772c300, 0x418000, 0x0, 0x0, 0x0)
05:16:40 tmpnode-rpc-stress-client-04:  /usr/local/google/home/veyron/workspace/vanadium-go-rpc-stress/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:914 +0xa7
05:16:40 tmpnode-rpc-stress-client-04: github.com/cosnicolaou/llog.(*Log).output(0xc8200fb040, 0xc800000003, 0xc8202720c0, 0x10da032, 0x9, 0x73)
05:16:40 tmpnode-rpc-stress-client-04:  /usr/local/google/home/veyron/workspace/vanadium-go-rpc-stress/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:868 +0x221
05:16:40 tmpnode-rpc-stress-client-04: github.com/cosnicolaou/llog.(*Log).PrintDepth(0xc8200fb040, 0x3, 0x1, 0xc8213ec5f0, 0x1, 0x1)
05:16:40 tmpnode-rpc-stress-client-04:  /usr/local/google/home/veyron/workspace/vanadium-go-rpc-stress/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:818 +0x1b3
05:16:40 tmpnode-rpc-stress-client-04: v.io/x/lib/vlog.(*Logger).FatalDepth(0xc820015e80, 0x1, 0xc8213ec5f0, 0x1, 0x1)
05:16:40 tmpnode-rpc-stress-client-04:  /usr/local/google/home/veyron/workspace/vanadium-go-rpc-stress/root/release/go/src/v.io/x/lib/vlog/log.go:325 +0x54
05:16:40 tmpnode-rpc-stress-client-04: v.io/v23/context.(*T).Fatalf(0xc820049810, 0xd71d60, 0x1d, 0xc820785e08, 0x1, 0x1)
05:16:40 tmpnode-rpc-stress-client-04:  /usr/local/google/home/veyron/workspace/vanadium-go-rpc-stress/root/release/go/src/v.io/v23/context/wraplog.go:64 +0x146
05:16:40 tmpnode-rpc-stress-client-04: v.io/x/ref/runtime/internal/rpc/stress/internal.CallSumStream(0xc820049810, 0x7ffdf8978e14, 0x23, 0x64, 0x2710, 0xc8201b1d80)
05:16:40 tmpnode-rpc-stress-client-04:  /usr/local/google/home/veyron/workspace/vanadium-go-rpc-stress/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stress/internal/client.go:115 +0x6ab
05:16:40 tmpnode-rpc-stress-client-04: main.runStressTest.func1(0xc82000a390, 0x3, 0x3, 0xc820049810, 0xc820136f60)
05:16:40 tmpnode-rpc-stress-client-04:  /usr/local/google/home/veyron/workspace/vanadium-go-rpc-stress/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stress/stress/stress.go:77 +0x19b
05:16:40 tmpnode-rpc-stress-client-04: created by main.runStressTest
05:16:40 tmpnode-rpc-stress-client-04:  /usr/local/google/home/veyron/workspace/vanadium-go-rpc-stress/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stress/stress/stress.go:87 +0x5e5
05:16:40 tmpnode-rpc-stress-client-04: ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255]. See https://cloud.google.com/compute/docs/troubleshooting#ssherrors for troubleshooting hints.
05:16:40 tmpnode-rpc-stress-client-04: [run] delete tmpdir "./tmp_712B1A6CDB20ABFB"
05:16:40 tmpnode-rpc-stress-client-04: Warning: Permanently added '104.197.112.92' (ECDSA) to the list of known hosts.
05:16:40 tmpnode-rpc-stress-client-04 FAIL: vcloud.go:310: Last("gcloud", "compute", "ssh", "veyron@tmpnode-rpc-stress-client-04", "--project", "vanadium-internal", "--zone", "us-central1-f", "--command", "cd ./tmp_712B1A6CDB20ABFB ; ./stress stress -workers 8 -max-chunk-count 100 -max-payload-size 10000 -duration 1h0m0s -format json /tmpnode-rpc-stress-server-00:10000 /tmpnode-rpc-stress-server-01:10000 /tmpnode-rpc-stress-server-02:10000"): exit status 255
```

@suharshs @mattr-google

**Comment by ghost** [comment]
This is a dup of #1029
