### ISSUE TITLE
Syncbase error: corrupt database

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#1037]
https://veyron.corp.google.com/jenkins/job/release-candidate-2-test/ARCH=amd64,OS=linux,TEST=vanadium-integration-test/570/console

```
09:52:50 --- PASS: TestV23RestartabilityAppDBCorruption (1.14s)
09:52:50    restartability_v23_test.go:480: syncbased terminated
09:52:50        stdout: 
09:52:50        stderr: I0105 09:50:08.683179    5814 funcs.go:22] Read permissions from command line flag: {"Read":{"In":["root:u:client"],"NotIn":null},"Resolve":{"In":["root:u:client"],"NotIn":null},"Write":{"In":["root:u:client"],"NotIn":null}}
09:52:50        I0105 09:50:08.698436    5814 funcs.go:22] Using persisted permissions: {"Read":{"In":["root:u:client"],"NotIn":null},"Resolve":{"In":["root:u:client"],"NotIn":null},"Write":{"In":["root:u:client"],"NotIn":null}}
09:52:50        E0105 09:50:08.700003    5814 funcs.go:94] leveldb /home/veyron/tmp/vit/439261795/495947250/apps/6131/dbs/6431-8bf757c5e854fb1fb107ddc47ab25bbf2e1e8e244780f62c3b676c1feb63abc7/leveldb is corrupt.  Moving aside. syncbased: Internal error: Corruption: checksum mismatch
09:52:50        E0105 09:50:08.700629    5814 funcs.go:94] app a1, database d1 is corrupt, deleting the app's reference to it
09:52:50        F0105 09:50:08.700730    5814 main.go:46] server.NewService() failed: syncbased: Internal error: syncbased: database corrupt, moved to /home/veyron/tmp/vit/439261795/495947250/apps/6131/dbs/6431-8bf757c5e854fb1fb107ddc47ab25bbf2e1e8e244780f62c3b676c1feb63abc7/leveldb.corrupt.2016-01-05T09:50:08-08:00; client must create a new database
09:52:50        goroutine 1 [running]:
09:52:50        github.com/cosnicolaou/llog.stacks(0xc820293000, 0x418000, 0x0, 0x0, 0x0)
09:52:50            /home/veyron/workspace/rc/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:914 +0xa7
09:52:50        github.com/cosnicolaou/llog.(*Log).output(0xc8200ca8c0, 0xc800000003, 0xc8203a0000, 0x131b1b9, 0x7, 0x2e)
09:52:50            /home/veyron/workspace/rc/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:868 +0x221
09:52:50        github.com/cosnicolaou/llog.(*Log).PrintDepth(0xc8200ca8c0, 0x3, 0x1, 0xc82017fe20, 0x2, 0x2)
09:52:50            /home/veyron/workspace/rc/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:818 +0x1b3
09:52:50        github.com/cosnicolaou/llog.(*Log).Print(0xc8200ca8c0, 0x3, 0xc82017fe20, 0x2, 0x2)
09:52:50            /home/veyron/workspace/rc/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:799 +0x50
09:52:50        v.io/x/lib/vlog.Fatal(0xc82017fe20, 0x2, 0x2)
09:52:50            /home/veyron/workspace/rc/root/release/go/src/v.io/x/lib/vlog/funcs.go:102 +0x4c
09:52:50        main.Serve(0xc820282d70, 0x0, 0x0, 0x0, 0x0, 0xc82019bfb0)
09:52:50            /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/services/syncbase/syncbased/main.go:46 +0x5a9
09:52:50        main.main()
09:52:50            /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/services/syncbase/syncbased/v23_main.go:21 +0x52
```

**Comment by ivanpi-mtv** [comment]
Working as intended.
