### ISSUE TITLE
baku-java-test is flaky

### ISSUE THREAD

**Issue by tatatodd** [vanadium/issues#1094]
@aghassemi @jwnichls [assigning to build cop, feel free to reassign]

My presubmits have seen baku-java-test repeatedly flaking out.  Example below.  I'm TBR'ing since it's too painful to watch it fail repeatedly.

https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=baku-java-test/18966/console

```
23:42:34 io.v.baku.toolkit.blessings.AccountManagerBlessingsFragmentTest > initializationError FAILED
23:42:34     java.lang.TypeNotPresentException: Type org.robolectric.RobolectricGradleTestRunner not present
23:42:34 
23:42:34         Caused by:
23:42:34         java.lang.ClassNotFoundException: org.robolectric.RobolectricGradleTestRunner
23:42:34 
23:42:34 io.v.baku.toolkit.blessings.ActivityBlessingsSeekerTest > testBlessingsFromManager FAILED
23:42:34     java.lang.NoSuchMethodError: io.v.baku.toolkit.blessings.BlessingsUtils.readSharedPrefs(Landroid/content/Context;)Lio/v/v23/security/Blessings;
23:42:34         at io.v.baku.toolkit.blessings.ActivityBlessingsSeekerTest.testBlessingsFromManager(ActivityBlessingsSeekerTest.java:65)
23:42:34 
23:42:34 io.v.baku.toolkit.blessings.ActivityBlessingsSeekerTest > testBlessingsFromProvider FAILED
23:42:34     rx.exceptions.OnErrorNotImplementedException
23:42:34         at rx.Observable$27.onError(Observable.java:7996)
23:42:34         at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
23:42:34         at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
23:42:34         at rx.observers.SerializedObserver.onError(SerializedObserver.java:159)
23:42:34         at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:79)
23:42:34         at rx.internal.operators.OperatorConcat$ConcatSubscriber.onError(OperatorConcat.java:142)
23:42:34         at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onError(OperatorConcat.java:208)
23:42:34         at rx.internal.operators.OperatorIgnoreElements$1.onError(OperatorIgnoreElements.java:47)
23:42:34         at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:199)
23:42:34         at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:48)
23:42:34         at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
23:42:34         at rx.Observable$2.call(Observable.java:162)
23:42:34         at rx.Observable$2.call(Observable.java:154)
23:42:34         at rx.Observable.unsafeSubscribe(Observable.java:8171)
23:42:34         at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:172)
23:42:34         at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:136)
23:42:34         at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79)
23:42:34         at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:97)
23:42:34         at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:73)
23:42:34         at rx.Subscriber.setProducer(Subscriber.java:211)
23:42:34         at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:49)
23:42:34         at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:32)
23:42:34         at rx.Observable$2.call(Observable.java:162)
23:42:34         at rx.Observable$2.call(Observable.java:154)
23:42:34         at rx.Observable.subscribe(Observable.java:8264)
23:42:34         at rx.Observable.subscribe(Observable.java:8231)
23:42:34         at rx.Observable.subscribe(Observable.java:7987)
23:42:34         at io.v.baku.toolkit.blessings.ActivityBlessingsSeekerTest.testBlessingsFromProvider(ActivityBlessingsSeekerTest.java:90)
23:42:34 
23:42:34         Caused by:
23:42:34         java.lang.NullPointerException
23:42:34             at io.v.android.libs.security.BlessingsManager.getBlessings(BlessingsManager.java:50)
23:42:34             at io.v.baku.toolkit.blessings.ActivityBlessingsSeeker.refreshBlessings(ActivityBlessingsSeeker.java:95)
23:42:34             at io.v.baku.toolkit.blessings.ActivityBlessingsSeeker.lambda$new$89(ActivityBlessingsSeeker.java:76)
23:42:34             at io.v.baku.toolkit.blessings.ActivityBlessingsSeeker.access$lambda$1(ActivityBlessingsSeeker.java)
23:42:34             at io.v.baku.toolkit.blessings.ActivityBlessingsSeeker$$Lambda$3.call(Unknown Source)
23:42:34             at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
23:42:34             ... 18 more
```

**Comment by aghassemi** [comment]
@AsturaPhoenix looking at the trends here https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=baku-java-test/buildTimeTrend looks like it stated becoming very flaky around 3pm on 26th.

**Comment by aghassemi** [comment]
+@spetrovic77 for possible insights.

**Comment by aghassemi** [comment]
@AsturaPhoenix This has started failing on Linux quite often today as well. https://veyron.corp.google.com/jenkins/job/baku-java-test/

**Comment by AsturaPhoenix** [comment]
I recently put in an increase to this timeout but it's behind CR. Bumping
it to the head of the line as a TBR (but keeping this issue open for
further investigation to make sure it's just a slowdown in Jenkins and not
an actual regression in the method blocking).

**Comment by AsturaPhoenix** [comment]
To clarify, I'm fixing the blocking-method flakiness. I have no idea why the Robolectric thing is happening.

**Comment by aghassemi** [comment]
Thanks! Recent failure seem only related to `testJoinAlreadyMounted` test

**Comment by sjamesr** [comment]
The robolectric failure shouldn't have happened after
https://vanadium-review.googlesource.com/#/c/19252/

**Comment by AsturaPhoenix** [comment]
Excellent! https://vanadium-review.googlesource.com/#/c/19336/ is in. It looks like one of the failures took > 400 ms, but the rest should be good now. I'll investigate to see if I can set a much more conservative timeout to assert on (> 5s).
