### ISSUE TITLE
unlock of unlocked mutex on attempt to create/run a server 

### ISSUE THREAD

**Issue by monopole** [vanadium/issues#1106]
In [moments](https://vanadium.googlesource.com/release.java/+/master/projects/moments/), step 3 crashes
1) create a server (V.withNewServer)
2) let it run a bit, then cancel the associated context
3) attempt to create a new server - crash:

02-01 15:31:12.687 10067-0/io.v.moments E/Go: panic: sync: unlock of unlocked mutex
02-01 15:31:12.687 10067-0/io.v.moments E/Go: goroutine 51 [running, locked to thread]:
02-01 15:31:12.687 10067-0/io.v.moments E/Go: sync.(_Mutex).Unlock(0xbfe13f38)
02-01 15:31:12.687 10067-0/io.v.moments E/Go:   /usr/local/google/home/sjr/vanadium_root/profiles/go/arm_android_armv7/560937434d5f2857bb69e0a6881a38201a197a8d/src/sync/mutex.go:109 +0xa0
02-01 15:31:12.687 10067-0/io.v.moments E/Go: v.io/x/ref/runtime/internal/flow/manager.(_manager).Listen(0xbfe10af0, 0xbfe3a300, 0xe0832750, 0x3, 0xbfcb220a, 0x2, 0xf3bae250, 0xbfd0d100)
02-01 15:31:12.687 10067-0/io.v.moments E/Go:   /usr/local/google/home/sjr/vanadium_root/release/go/src/v.io/x/ref/runtime/internal/flow/manager/manager.go:182 +0x368
02-01 15:31:12.690 10067-0/io.v.moments E/Go: v.io/x/ref/runtime/internal/rpc.(_xserver).listen(0xbfdd6210, 0xbfe3a300, 0xbfcb28b0, 0x1, 0x1, 0x0, 0x0, 0xf3bae518, 0xbfcf60e0)
02-01 15:31:12.690 10067-0/io.v.moments E/Go:   /usr/local/google/home/sjr/vanadium_root/release/go/src/v.io/x/ref/runtime/internal/rpc/xserver.go:319 +0x228
02-01 15:31:12.691 10067-0/io.v.moments E/Go: v.io/x/ref/runtime/internal/rpc.WithNewDispatchingServer(0xbfe3a000, 0x0, 0x0, 0xf3a793e8, 0xbfcb3598, 0xbfb70510, 0xbfcb35b0, 0x2, 0x2, 0x0, ...)
02-01 15:31:12.691 10067-0/io.v.moments E/Go:   /usr/local/google/home/sjr/vanadium_root/release/go/src/v.io/x/ref/runtime/internal/rpc/xserver.go:190 +0x1288
02-01 15:31:12.691 10067-0/io.v.moments E/Go: v.io/x/ref/runtime/internal/rt.(_Runtime).WithNewDispatchingServer(0xbfb34360, 0xbfdbbb00, 0x0, 0x0, 0xf3a793e8, 0xbfcb3598, 0xbfcb35b0, 0x2, 0x2, 0x0, ...)
02-01 15:31:12.691 10067-0/io.v.moments E/Go:   /usr/local/google/home/sjr/vanadium_root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:456 +0x150
02-01 15:31:12.691 10067-0/io.v.moments E/Go: v.io/v23.WithNewDispatchingServer(0xbfdbbb00, 0x0, 0x0, 0xf3a793e8, 0xbfcb3598, 0xbfdc5b90, 0x1, 0x1, 0xdffb6634, 0x0, ...)
02-01 15:31:12.691 10067-0/io.v.moments E/Go:   /usr/local/google/home/sjr/vanadium_root/release/go/src/v.io/v23/model.go:341 +0x9c
02-01 15:31:12.691 10067-0/io.v.moments E/Go: v.io/x/jni/impl/google/rt.Java_io_v_impl_google_rt_VRuntimeImpl_nativeWithNewServer(0xab07a608, 0xae77e35c, 0xae77e360, 0xae77e364, 0xae77e368, 0xae77e36c, 0xbfd13f5c)
02-01 15:31:12.691 10067-0/io.v.moments E/Go:   /usr/local/google/home/sjr/vanadium_root/release/go/src/v.io/x/jni/impl/google/rt/jni.go:140 +0x234
02-01 15:31:12.691 10067-0/io.v.moments E/Go: v.io/x/jni/impl/google/rt._cgoexpwrap_a65093a11ab9_Java_io_v_impl_google_rt_VRuntimeImpl_nativeWithNewServer(0xab07a608, 0xae77e35c, 0xae77e360, 0xae77e364, 0xae77e368, 0xae77e36c, 0x0)
02-01 15:31:12.691 10067-0/io.v.moments E/Go:   ??:0 +0x88

**Comment by monopole** [comment]
To repro
1. start moments
2. take a picture
3. advertise it (click the on/off slider next to the photo)
4. stop advertisement
5. attempt to start advertising again

The last step tries to create and start a new server, which crashes.

The start server call is here: https://vanadium.googlesource.com/release.java/+/master/projects/moments/app/src/main/java/io/v/moments/model/AdvertiserImpl.java#70

The same thing happens if you comment out all the advertising/discovery stuff.

So i don't think any advertising/discovery code is involved.
