### ISSUE TITLE
android discovery: secondary attempts to advertise always fail

### ISSUE THREAD

**Issue by monopole** [vanadium/issues#1119]
In the [moments app](https://vanadium.googlesource.com/release.java/+/master/projects/moments/) at head, 

The sequence start and stop advertising works fine:

```
  baseContext = V.init(androidContext)
  discovery = V.newDiscovery(baseContext)
  VContext context = baseContext.withTimeout(Duration.standardHours(1));
  advContext = discovery.advertise(context, service, patterns);
  advContext.cancel()
```

But following this with a new attempt to start advertising

```
  VContext context = baseContext.withTimeout(Duration.standardHours(1));
 advContext = discovery.advertise(context, service, patterns);
```

always fails with

```
02-03 14:22:13.559 9935-9935/io.v.moments D/V23Manager: Failure to start advertising.
                                                        java.util.concurrent.CancellationException: Task was cancelled.
                                                            at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:392)
                                                            at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
                                                            at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
                                                            at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
                                                            at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
                                                            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1308)
                                                            at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
                                                            at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
                                                            at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
                                                            at com.google.common.util.concurrent.AbstractFuture.cancel(AbstractFuture.java:134)
                                                            at com.google.common.util.concurrent.Futures$FallbackFuture.cancel(Futures.java:500)
                                                            at com.google.common.util.concurrent.Futures$FallbackFuture$1$1.onFailure(Futures.java:485)
                                                            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1313)
                                                            at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
                                                            at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:106)
                                                            at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1322)
                                                            at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:476)
                                                            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1313)
                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                            at android.os.Looper.loop(Looper.java:148)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                         Caused by: java.util.concurrent.CancellationException: Future.cancel() was called.
                                                            at com.google.common.util.concurrent.AbstractFuture$Sync.complete(AbstractFuture.java:378)
                                                            at com.google.common.util.concurrent.AbstractFuture$Sync.cancel(AbstractFuture.java:355)
                                                            at com.google.common.util.concurrent.AbstractFuture.cancel(AbstractFuture.java:131)
                                                            at com.google.common.util.concurrent.Futures$FallbackFuture.cancel(Futures.java:500) 
                                                            at com.google.common.util.concurrent.Futures$FallbackFuture$1$1.onFailure(Futures.java:485) 
                                                            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1313) 
                                                            at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) 
                                                            at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:106) 
                                                            at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1322) 
                                                            at com.google.common.util.concurrent.Futures$FallbackFuture$1.onFailure(Futures.java:476) 
                                                            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1313) 
                                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                            at android.os.Looper.loop(Looper.java:148) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by spetrovic77** [comment]
The issue here is that in advertiseStop(), you're canceling mServerCtx, which is derived from mV23Ctx in makeServerContext().  The unfortunate thing is that canceling mServeCtx does cancel mV23Ctx as well.  Sigh.

This was intentional (see comments for VContext.withValue()), because unlike Go we don't want to return both VContext and cancelation function on VContext.withCancel() and hence we keep the cancelation function as part of VContext.

As a fix, in getListenContext(), you should derive a new context from mV23Ctx via withCancel().  I'll think of what we can do for these oversights not to happen.
