### ISSUE TITLE
[Vanadium-go-bench] v.iov23/nosql test failing

### ISSUE THREAD

**Issue by ankurtaly** [vanadium/issues#1134]
The following test seems to be timing out:

jiri go test -tags=leveldb -timeout 1h -v -bench . -run "^(BenchmarkTinyPut|BenchmarkTinyGet|BenchmarkTinyDelete|BenchmarkTinyScan|BenchmarkTinyExec|BenchmarkTinyWatchPuts|BenchmarkTinyWatchOnePut|BenchmarkHugePut|BenchmarkHugeGet|BenchmarkHugeDelete|BenchmarkHugeScan|BenchmarkHugeExec|BenchmarkHugeWatchPuts|BenchmarkHugeWatchOnePut)$" v.io/v23/syncbase/nosql

I suspect this is related to:
https://vanadium-review.googlesource.com/#/c/19549/

**Comment by ghost** [comment]
Actually this has been happening ever since @asadovsky  checked in his change:

https://vanadium-review.googlesource.com/#/c/19129/

But his changed was committed during the unfortunate period when we stopped running jenkins tests accidentally.  I'll try to figure this out tomorrow.

**Comment by asadovsky** [comment]
Here are two log files, the first from running on my local Linux workstation, and the second from running on a Jenkins node (jenkins-node42):
[local_log.txt](https://github.com/vanadium/issues/files/124144/local_log.txt)
[jenkins_log.txt](https://github.com/vanadium/issues/files/124143/jenkins_log.txt)

From these logs, it appears that most of the benchmarks take approximately the same amount of time to run on Jenkins vs. locally. However, on Jenkins the BenchmarkHugeWatchOnePut test just stalls. This appears to be the relevant stack trace:

goroutine 38596 [chan receive, 58 minutes]:
v.io/v23/syncbase/nosql_test.runWatchOnePutBenchmark(0xc8207c5900, 0xef0fe0, 0xc820e70300)
    /home/veyron/jenkins/workspace/vanadium-go-bench/root/release/go/src/v.io/v23/syncbase/nosql/benchmark_test.go:239 +0x363
v.io/v23/syncbase/nosql_test.BenchmarkHugeWatchOnePut(0xc8207c5900)
    /home/veyron/jenkins/workspace/vanadium-go-bench/root/release/go/src/v.io/v23/syncbase/nosql/benchmark_test.go:297 +0x43
testing.(_B).runN(0xc8207c5900, 0x64)
    /home/veyron/jenkins/workspace/vanadium-go-bench/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/benchmark.go:124 +0x9a
testing.(_B).launch(0xc8207c5900)
    /home/veyron/jenkins/workspace/vanadium-go-bench/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/benchmark.go:216 +0x131
created by testing.(*B).run
    /home/veyron/jenkins/workspace/vanadium-go-bench/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/benchmark.go:179 +0x54

The stack trace suggests this line (added by Matt's v.io/c/19549) is somehow the culprit: https://github.com/vanadium/go.v23/blob/b14e0cf35be200dc7c47202b4bbd2ca4ecda7d73/syncbase/nosql/benchmark_test.go#L239

I'm not sure why the test was failing before Matt's CL. Unfortunately the logs on Jenkins don't include the detailed logs or stack trace.

The log from my Jenkins run also has these lines printed immediately before the SIGQUIT, which is a bit strange:
E0209 16:44:54.791100    2065 funcs.go:94] vclockd: DoNtpUpdate: failed to fetch NTP time: vclock: NtpSync: no NTP server
E0209 17:42:44.177558    2065 funcs.go:94] vclockd: DoNtpUpdate: failed to fetch NTP time: vclock: NtpSync: no NTP server
E0209 17:42:44.380572    2065 funcs.go:94] vclockd: DoNtpUpdate: failed to fetch NTP time: vclock: NtpSync: no NTP server
E0209 17:42:45.084555    2065 funcs.go:94] vclockd: DoNtpUpdate: failed to fetch NTP time: vclock: NtpSync: no NTP server
E0209 17:42:47.046393    2065 funcs.go:94] vclockd: DoNtpUpdate: failed to fetch NTP time: vclock: NtpSync: no NTP server
...

`DoNtpUpdate` should be running once per hour, so I'm not sure why it runs in such rapid succession immediately before the SIGQUIT.

**Comment by asadovsky** [comment]
Attaching the log from another node42 run:
[jenkins_log2.txt](https://github.com/vanadium/issues/files/125378/jenkins_log2.txt)

This one stalls in `BenchmarkTinyWatchOnePut` (more specifically, at the same place as the previous run, in `benchmark_test.go`):
https://github.com/vanadium/go.v23/blob/b14e0cf35be200dc7c47202b4bbd2ca4ecda7d73/syncbase/nosql/benchmark_test.go#L239

Btw, I think I understand a bit more about those `DoNtpUpdate` logs now - there's one of those per benchmark, and each benchmark starts a separate in-process Syncbase server. Digging around the code, I think what's happening is that we aren't exiting all Syncbase goroutines on server shutdown. See this TODO:
http://cs/#vanadium/release/go/src/v.io/x/ref/services/syncbase/server/service.go&l=272&rcl=cba3b76aecb09f3d9432d7bbcaaf6090a5dd2143

**Comment by ghost** [comment]
I got a different stack than Adam.  For me, if I run a bunch of tests first, then sometimes the HugePuts benchmark hangs after receiving only 90-something of the 100 results it was expecting.  @hpucha Do you have any tips for me to figure out where this is getting hung up?

[out.txt](https://github.com/vanadium/issues/files/128711/out.txt)

**Comment by ghost** [comment]
Well, nobody ever fixed this bug, we just disabled the test.  I haven't had time to investigate more why this would happen.  Do you have time?

**Comment by aghassemi** [comment]
oh I thought it was fixed (since it has been green) and we forgot to close the bug. I will take it.
