### ISSUE TITLE
vanadium-java-test on darwin is flaky

### ISSUE THREAD

**Issue by jinjingforever** [vanadium/issues#1173]
It timed out a couple of times with the same error:

:lib:test (Thread[main,5,main]) started.
:lib:test
Executing task ':lib:test' (up-to-date check took 0.012 secs) due to:
  Task.upToDateWhen is false.
Starting process 'Gradle Test Executor 3'. Working directory: /Users/veyron/jenkins/root/1/release/java/lib Command: /Users/veyron/jenkins/tools/hudson.model.JDK/Java_8/bin/java -Djava.library.path=build/libs -Djava.security.manager=jarjar.org.gradle.process.internal.child.BootstrapSecurityManager -XX:+UnlockDiagnosticVMOptions -XX:-LogEvents -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /Users/veyron/.gradle/caches/2.3/workerMain/gradle-worker.jar jarjar.org.gradle.process.internal.launcher.GradleWorkerMain 'Gradle Test Executor 3'
Successfully started process 'Gradle Test Executor 3'
Gradle Test Executor 3 started executing tests.
E0225 16:14:05.985315   58207 server.go:228] Dispatcher: *server.dispatcher, Status:[{Stopping false [] [@6@tcp@127.0.0.1:57903@@fa20a6065d02cf5383eccd15547abbb0@s@veyron@Veyrons-Mac-Pro-1.local-58207@@] map[{tcp localhost:0}:<nil>] map[] 0xc820339e00}]: Timed out waiting for active requests to complete
E0225 16:14:06.694684   58207 server.go:228] Dispatcher: *server.dispatcher, Status:[{Stopping false [] [@6@tcp@127.0.0.1:57923@@c50930925e99cac0542a015dc1d2ea19@s@veyron@Veyrons-Mac-Pro-1.local-58207@@] map[{tcp localhost:0}:<nil>] map[] 0xc820e178c0}]: Timed out waiting for active requests to complete

io.v.v23.vom.BinaryDecoderTest > testDecodeVExceptionBadParams STANDARD_ERROR
    Couldn't determine VDL type for param reflect type interface java.util.List.  This param will be dropped if ever VOM-encoded
    Couldn't determine VDL type for param reflect type interface java.util.Map.  This param will be dropped if ever VOM-encoded
    Dropping parameter #0 ([3]) whose type doesn't have a matching VdlType.
    Dropping parameter #1 ({4=}) whose type doesn't have a matching VdlType.

io.v.x.jni.test.fortune.FortuneTest > testLameDuck FAILED
    junit.framework.AssertionFailedError: get() that starts after server context cancel should fail
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.TestCase.fail(TestCase.java:227)
        at io.v.x.jni.test.fortune.FortuneTest.testLameDuck(FortuneTest.java:190)
Gradle Test Executor 3 finished executing tests.

Could you please take a look? Thanks!
- Jing

**Comment by caprita** [comment]
Is this still an issue?

**Comment by jinjingforever** [comment]
Yes I think so.

https://veyron.corp.google.com/jenkins/job/vanadium-java-test/7428/OS=darwin/testReport/junit/(root)/vanadium-java-test/Internal_Error/
