### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1315]
I think this could be related to Go 1.6 changes being stricter about when you can have Go pointers to Go pointers. (For example, https://github.com/go-gl/gl/issues/31)

My Syncbase (on Android) crashes and restarts arbitrarily. Here are a few stack traces that I've collected.

This one is flow/signing related:

```
04-29 20:06:08.355 7653-0/io.v.todos.syncbase E/Go: panic: runtime error: cgo argument has Go pointer to Go pointer
04-29 20:06:08.355 7653-0/io.v.todos.syncbase E/Go: goroutine 160198 [running]:
04-29 20:06:08.355 7653-0/io.v.todos.syncbase E/Go: panic(0xe1b9a658, 0xc3e63728)
04-29 20:06:08.355 7653-0/io.v.todos.syncbase E/Go:     /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/panic.go:464 +0x370
04-29 20:06:08.356 7653-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.jMethodID(0xab4ad078, 0xc0c00001, 0xe1c8e050, 0x4, 0xc3ac6ae0, 0x24, 0x0, 0x0, 0x0)
04-29 20:06:08.356 7653-0/io.v.todos.syncbase E/Go:     /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:73 +0x194
04-29 20:06:08.356 7653-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.setupMethodCall(0xab4ad078, 0x20057e, 0xe1c8e050, 0x4, 0xc4fdfbb4, 0x2, 0x2, 0xc374b7a0, 0x1e, 0xc4fdfba4, ...)
04-29 20:06:08.356 7653-0/io.v.todos.syncbase E/Go:     /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:98 +0xc4
04-29 20:06:08.356 7653-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.CallObjectMethod(0xab4ad078, 0x20057e, 0xe1c8e050, 0x4, 0xc4fdfbb4, 0x2, 0x2, 0xc374b7a0, 0x1e, 0xc4fdfba4, ...)
04-29 20:06:08.356 7653-0/io.v.todos.syncbase E/Go:     /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:130 +0x2d8
04-29 20:06:08.356 7653-0/io.v.todos.syncbase E/Go: v.io/x/jni/v23/security.(*signer).Sign(0xc0d951b8, 0xe2183ec6, 0x2, 0x2, 0xc0f389a0, 0x15c, 0x160, 0x0, 0x0, 0x0, ...)
04-29 20:06:08.356 7653-0/io.v.todos.syncbase E/Go:     /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/v23/security/signer.go:46 +0x358
04-29 20:06:08.357 7653-0/io.v.todos.syncbase E/Go: v.io/v23/security.(*principal).Sign(0xc0e7bbc0, 0xc0f389a0, 0x15c, 0x160, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
04-29 20:06:08.357 7653-0/io.v.todos.syncbase E/Go:     /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/v23/security/principal.go:141 +0xa4
04-29 20:06:08.357 7653-0/io.v.todos.syncbase E/Go: v.io/x/ref/runtime/internal/flow/conn.(*Conn).dialHandshake(0xc2699680, 0xc4668e40, 0xa, 0xe, 0xf00b97e8, 0xc4560920, 0xc3e63708, 0x1, 0x1, 0x0, ...)
04-29 20:06:08.357 7653-0/io.v.todos.syncbase E/Go:     /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/runtime/internal/flow/conn/auth.go:75 +0x75c
04-29 20:06:08.357 7653-0/io.v.todos.syncbase E/Go: v.io/x/ref/runtime/internal/flow/conn.NewDialed.func1(0xc688b558, 0xc3b87c40, 0xf00b98f0, 0xc3e686a0, 0xc4668e40, 0xc3e686f0, 0xc3e68710, 0xc3e68728, 0xc688b588, 0xa, ...)
04-29 20:06:08.357 7653-0/io.v.todos.syncbase E/Go:     /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/runtime/internal/flow/conn/conn.go:200 +0x198
04-29 20:06:08.357 7653-0/io.v.todos.syncbase E/Go: created by v.io/x/ref/runtime/internal/flow/conn.NewDialed
04-29 20:06:08.357 7653-0/io.v.todos.syncbase E/Go:     /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/runtime/internal/flow/conn/conn.go:201 +0x984
04-29 20:06:08.357 7653-7722/io.v.todos.syncbase A/libc: Fatal signal 13 (SIGPIPE), code 0 in tid 7722 (Thread-890)
```

Another one, related to vom/vdl:

```
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: panic: runtime error: cgo argument has Go pointer to Go pointer
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: goroutine 3782 [running]:
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: panic(0xe1b9a658, 0xc15efb88)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/panic.go:464 +0x370
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.JByteArray(0xab3eb4d0, 0xc0eb1a40, 0xc1, 0x1ad, 0x1, 0x0, 0x0)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/util.go:441 +0x10c
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.jByteArrayValue(0xab3eb4d0, 0xe1a40f50, 0xc1836990, 0x0, 0x0, 0xc0fe5918)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/value.go:194 +0x138
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.jValue(0xab3eb4d0, 0xe1a40f50, 0xc1836990, 0xc0c2cf6e, 0x2, 0x0, 0x0, 0xc0fe59c0)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/value.go:80 +0x670
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.jArgArray(0xab3eb4d0, 0xc0fe5bb0, 0x2, 0x2, 0xc0fe5bc0, 0x2, 0x2, 0x0, 0xc15efb80, 0x0, ...)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:39 +0x30c
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.setupStaticMethodCall(0xab3eb4d0, 0x100412, 0xe1c8a6d8, 0x6, 0xc0fe5bc0, 0x2, 0x2, 0xc0c8b080, 0x12, 0xc0fe5bb0, ...)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:117 +0x108
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.CallStaticObjectMethod(0xab3eb4d0, 0x100412, 0xe1c8a6d8, 0x6, 0xc0fe5bc0, 0x2, 0x2, 0xc0c8b080, 0x12, 0xc0fe5bb0, ...)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:240 +0x2d8
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.JVomDecodeWithType(0xab3eb4d0, 0xc0eb1a40, 0xc1, 0x1ad, 0x100416, 0x0, 0x0, 0x0)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/coding.go:60 +0x288
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.JVomCopyWithType(0xab3eb4d0, 0xe1c0c600, 0xc1883bc0, 0x100416, 0x2, 0x0, 0x0)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/coding.go:76 +0x98
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.JVomCopy(0xab3eb4d0, 0xe1c0c600, 0xc1883bc0, 0x100416, 0xe1c0c600, 0x0, 0x0)
04-29 18:17:48.667 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/coding.go:66 +0x48
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.JVException(0xab3eb4d0, 0xf00b6358, 0xc1883bc0, 0xc1233c80, 0x0, 0x0)
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/util.go:172 +0x88
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.jVExceptionValue(0xab3eb4d0, 0xe1c0c600, 0xc1883bc0, 0x0, 0x0, 0x0)
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/value.go:182 +0x188
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.jValue(0xab3eb4d0, 0xe1c0c600, 0xc1883bc0, 0xc0c8b2c0, 0x1c, 0x0, 0x0, 0xc1233db8)
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/value.go:78 +0x55c
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.jArgArray(0xab3eb4d0, 0xc0fe5f50, 0x1, 0x1, 0xc0fe5f58, 0x1, 0x1, 0x0, 0xc15efb18, 0x0, ...)
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:39 +0x30c
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.setupMethodCall(0xab3eb4d0, 0x10005a6, 0xe1cdc3b0, 0x9, 0xc0fe5f58, 0x1, 0x1, 0xe1c8540c, 0x1, 0xc0fe5f50, ...)
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:102 +0x124
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.CallVoidMethod(0xab3eb4d0, 0x10005a6, 0xe1cdc3b0, 0x9, 0xc0fe5f58, 0x1, 0x1, 0xc0fe5f50, 0x1, 0x1, ...)
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:225 +0x84
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.CallbackOnFailure(0xab3eb4d0, 0x10005a6, 0xf00b6358, 0xc1883bc0)
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:466 +0x150
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.DoAsyncCall.func1(0xc1919450, 0x10005a6)
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:456 +0x1b0
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go: created by v.io/x/jni/util.DoAsyncCall
04-29 18:17:48.668 29896-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/call.go:460 +0x4c
```

And another one for client RPC:

```
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go: panic: runtime error: cgo argument has Go pointer to Go pointer
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go: goroutine 18 [running, locked to thread]:
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go: panic(0xe1b9a658, 0xc134cdd0)
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/panic.go:464 +0x370
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.GoByteArray(0xaaeeab68, 0xc0c00021, 0x0, 0x0, 0x0)
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/util.go:454 +0xe4
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go: v.io/x/jni/util.GoByteArrayArray(0xaaeeab68, 0xffe25b8c, 0x0, 0x0, 0x0, 0x0, 0x0)
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/util/util.go:505 +0x140
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go: v.io/x/jni/impl/google/rpc.decodeArgs(0xaaeeab68, 0xffe25b8c, 0x0, 0x0, 0x0, 0x0, 0x0)
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/impl/google/rpc/jni.go:253 +0x40
04-29 18:16:37.288 28553-0/io.v.todos.syncbase E/Go: v.io/x/jni/impl/google/rpc.Java_io_v_impl_google_rpc_ClientImpl_nativeStartCall(0xaaeeab68, 0xffe25b7c, 0x2c88, 0x0, 0xffe25b80, 0xffe25b84, 0xffe25b88, 0xffe25b8c, 0x0, 0x0, ...)
04-29 18:16:37.289 28553-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/impl/google/rpc/jni.go:300 +0xd8
04-29 18:16:37.289 28553-0/io.v.todos.syncbase E/Go: v.io/x/jni/impl/google/rpc._cgoexpwrap_ba5290df77b3_Java_io_v_impl_google_rpc_ClientImpl_nativeStartCall(0xaaeeab68, 0xffe25b7c, 0x2c88, 0x0, 0xffe25b80, 0xffe25b84, 0xffe25b88, 0xffe25b8c, 0x0, 0x0, ...)
04-29 18:16:37.289 28553-0/io.v.todos.syncbase E/Go:    ??:0 +0x6c
```

This final one is NOT the same error, but it might be related since it could be the reverse situation (where C is sending a reference back to Go).

```
E/keystore(  361): Error while importing keypair: -1
E/Go      ( 6711): panic: Reference 42975 doesn't exist.
E/Go      ( 6711): goroutine 11723 [running]:
E/Go      ( 6711): panic(0x9ff99fd0, 0x90ca3cd8)
E/Go      ( 6711):  /usr/local/google/home/aghassemi/git/v23/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/panic.go:464 +0x370
E/Go      ( 6711): v.io/x/jni/util.(*safeRefCounter).getVal(0x8f207d40, 0xa7df, 0x0, 0x0, 0x0)
E/Go      ( 6711):  /usr/local/google/home/aghassemi/git/v23/release/go/src/v.io/x/jni/util/ref.go:186 +0x1c4
E/Go      ( 6711): v.io/x/jni/util.GoRefValue(0xa7df, 0x0, 0x8f97bdb4)
E/Go      ( 6711):  /usr/local/google/home/aghassemi/git/v23/release/go/src/v.io/x/jni/util/ref.go:90 +0x38
E/Go      ( 6711): v.io/x/jni/impl/google/rpc.doStartCall(0x8f40da40, 0x8f2d0968, 0x904a5c70, 0xc1, 0x90aab8b4, 0x9, 0x0, 0x0, 0x0, 0xa7df, ...)
E/Go      ( 6711):  /usr/local/google/home/aghassemi/git/v23/release/go/src/v.io/x/jni/impl/google/rpc/jni.go:246 +0x38
E/Go      ( 6711): v.io/x/jni/impl/google/rpc.Java_io_v_impl_google_rpc_ClientImpl_nativeStartCall.func1(0x1, 0x0, 0x0)
E/Go      ( 6711):  /usr/local/google/home/aghassemi/git/v23/release/go/src/v.io/x/jni/impl/google/rpc/jni.go:301 +0xdc
E/Go      ( 6711): v.io/x/jni/util.DoAsyncCall.func1(0x905cb7c0, 0x100da6)
E/Go      ( 6711):  /usr/local/google/home/aghassemi/git/v23/release/go/src/v.io/x/jni/util/call.go:444 +0x1c
E/Go      ( 6711): created by v.io/x/jni/util.DoAsyncCall
E/Go      ( 6711):  /usr/local/google/home/aghassemi/git/v23/release/go/src/v.io/x/jni/util/call.go:460 +0x4c
```

@asimshankar @mattr-google

**Comment by AsturaPhoenix** [comment]
@sjamesr took a quick look and says there was a similar situation before where unsafe.Pointer was being used to store some kind of offset that wasn't actually a pointer. He also found possibly relevant https://groups.google.com/forum/#!searchin/golang-nuts/cgo$20argument$20has$20Go$20pointer$20to$20Go$20pointer/golang-nuts/gnH0nhPf36I/4Shly3gxEwAJ

**Comment by asadovsky** [comment]
+cc @asimshankar @tatatodd @mattr-google 

Per some discussions this morning, we plan to completely redo the Java->Syncbase bridge implementation (no more local RPCs; Java will talk directly to the Syncbase C/Cgo API via JNI), at which point we will no longer use the existing bindings. This issue should get resolved as a consequence of that. So, unless this is urgent, let's hold off on trying to fix it.

**Comment by ghost** [comment]
I looked a little, and came up with nothing.  I like Adam's thinking.

**Comment by afandria** [comment]
The crash occurs only every once in a while, so the app is mostly usable. We can wait.

**Comment by ghost** [comment]
Also, this error probably could be ignored in go1.6 since the collector isn't actually moving.  We could consider setting GODEBUG=cgocheck=0 to simply silence the error to reduce immediate pain.

**Comment by afandria** [comment]
Is that a flag we can set while compiling all the Vanadium binaries? For example,
`GODEBUG=cgocheck=0 jiri go install v.io/...`

**Comment by ghost** [comment]
Sadly no, it's an environment variable you have to set at run time.  I'm not sure how to do that in Android.  Maybe if you do set the variable in you java code before you load the vanadium .so it will work.
