### ISSUE TITLE
Discovery: Advertisement with visibility crashes due to lack of crypter (Java)

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1328]
Spoke with @jhahn21 and it looks like we need to initialize discovery with a crypter or something.

Error Message:

```
05-13 11:04:56.041 15214-0/io.v.todos.syncbase E/Go: panic: runtime error: invalid memory address or nil pointer dereference
05-13 11:04:56.041 15214-0/io.v.todos.syncbase E/Go: [signal 0xb code=0x1 addr=0x0 pc=0x9cd21f84]
05-13 11:04:56.041 15214-0/io.v.todos.syncbase E/Go: goroutine 17 [running, locked to thread]:
05-13 11:04:56.042 15214-0/io.v.todos.syncbase E/Go: panic(0x9d3c6998, 0x8c400038)
05-13 11:04:56.042 15214-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/panic.go:464 +0x370
05-13 11:04:56.042 15214-0/io.v.todos.syncbase E/Go: v.io/x/ref/lib/security/bcrypter.(*Crypter).Encrypt(0x0, 0x8c858c60, 0x8c551490, 0x6c, 0x8ca1c580, 0x20, 0x20, 0x0, 0x0, 0x0)
05-13 11:04:56.042 15214-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/lib/security/bcrypter/crypter.go:107 +0x220
05-13 11:04:56.042 15214-0/io.v.todos.syncbase E/Go: v.io/x/ref/lib/discovery.wrapSharedKey(0x8c858c60, 0x76e43aef, 0xe939b778, 0x6f22c15d, 0x67e848c0, 0x9b4f2287, 0x37c2ed08, 0xafb54b6f, 0x4fe5c141, 0x8c551490, ...)
05-13 11:04:56.042 15214-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/lib/discovery/cipher.go:115 +0xc0
05-13 11:04:56.042 15214-0/io.v.todos.syncbase E/Go: v.io/x/ref/lib/discovery.encrypt(0x8c858c60, 0x8ca673e0, 0x8ca1c380, 0x3, 0x3, 0x0, 0x0)
05-13 11:04:56.042 15214-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/lib/discovery/cipher.go:45 +0x1e8
05-13 11:04:56.043 15214-0/io.v.todos.syncbase E/Go: v.io/x/ref/lib/discovery.(*idiscovery).advertise(0x8c4640a0, 0x8c858c60, 0x2, 0x0, 0x8c4a83f0, 0x8ca1c380, 0x3, 0x3, 0x8c7d8210, 0x0, ...)
05-13 11:04:56.043 15214-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/lib/discovery/advertise.go:33 +0x1e0
05-13 11:04:56.043 15214-0/io.v.todos.syncbase E/Go: v.io/x/ref/lib/discovery.(*sdiscovery).Advertise(0x8c89dd40, 0x8c858c60, 0x8c4a83f0, 0x8ca1c380, 0x3, 0x3, 0x0, 0x0, 0x0)
05-13 11:04:56.043 15214-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/lib/discovery/session.go:23 +0x68
05-13 11:04:56.043 15214-0/io.v.todos.syncbase E/Go: v.io/x/jni/impl/google/discovery.Java_io_v_impl_google_lib_discovery_DiscoveryImpl_nativeAdvertise(0x78b22840, 0x6d67b47c, 0xb6, 0x0, 0x6d67b480, 0x6d67b484, 0x6d67b488, 0x6d67b48c)
05-13 11:04:56.043 15214-0/io.v.todos.syncbase E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/jni/impl/google/discovery/jni.go:130 +0x30c
05-13 11:04:56.043 15214-0/io.v.todos.syncbase E/Go: v.io/x/jni/impl/google/discovery._cgoexpwrap_b6b7994eabee_Java_io_v_impl_google_lib_discovery_DiscoveryImpl_nativeAdvertise(0x78b22840, 0x6d67b47c, 0xb6, 0x0, 0x6d67b480, 0x6d67b484, 0x6d67b488, 0x6d67b48c)
05-13 11:04:56.044 15214-0/io.v.todos.syncbase E/Go:    ??:0 +0x54
```

Issues:
- the error message is opaque. The real problem is that crypter was nil (the line that failed was `c.mu.RLock()`, but the error should be caught much earlier.
- We need to initialize a crypter; how do we do that? Is this documented?

@asadovsky @aghassemi This must be solved before we can implement private sharing with Syncbase.

The short-term workaround for TODOs will be to advertise publicly but add attributes that the scanner and advertiser can filter on. @AsturaPhoenix

**Comment by afandria** [comment]
Thanks for fixing the error message (in v.io/c/22425). How do we initialize the crypter in Go and Java?

**Comment by jhahn21** [comment]
We don't have an IBE server in prod / Java api yet and I don't think it is in our 6-week plan. @asimshankar ?
