### ISSUE TITLE
Re-enable testTimeout from io.v.v23.VFuturesTest

### ISSUE THREAD

**Issue by razvanm** [vanadium/issues#1359]
In https://github.com/vanadium/build/issues/80 we disabled `testTimeout` from `io.v.v23.VFuturesTest` because it was flaky. We should figure out what was wrong and re-enable it.

Sample failure:

```
io.v.v23.VFuturesTest > testTimeout FAILED
    java.lang.Exception: Unexpected exception, expected<io.v.v23.verror.TimeoutException> but was<io.v.v23.verror.CanceledException>

        Caused by:
        io.v.v23.verror.CanceledException: VExceptionTest: Canceled
            at io.v.v23.VFutures.sync(VFutures.java:64)
            at io.v.v23.VFuturesTest.testTimeout(VFuturesTest.java:69)
```

**Comment by razvanm** [comment]
The test was re-enabled in https://github.com/vanadium/java/commit/47599d075f7ec13b66066bcc01deacdb9658a7a8.
