### ISSUE TITLE
Syncbase database corruption

### ISSUE THREAD

**Issue by tatatodd** [vanadium/issues#1360]
@hpucha @rdvg @afandria @asadovsky @nlacasse 

We just noticed the todos app complaining about a corrupt database.  Here's the sequence of events.

First the app crashes.  We've seen this crash a few times now.  The crash is an invalid stack pointer in the Go gc code.  The likely culprit is our JNI or C code.  E.g. we're corrupting the stack or heap, or double-freeing some memory, or something like that.  Here's the logs for the crash:

```
[DAWN2] E/Go      : runtime: bad pointer in frame v.io/x/jni/util.JObjectArray at 0xbdbf9e2c: 0x9
[DAWN2] 
[DAWN2] E/Go      : fatal error: invalid stack pointer
[DAWN2] 
[DAWN2] E/Go      : runtime stack:
[DAWN2] 
[DAWN2] E/Go      : runtime.throw(0xde635010, 0x15)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/panic.go:530 +0x80 fp=0xa9bcd3f4 sp=0xa9bcd3e8
[DAWN2] 
[DAWN2] E/Go      : runtime.adjustpointers(0xbdbf9e28, 0xa9bcd4b8, 0xa9bcd698, 0xde780080)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/stack.go:579 +0x288 fp=0xa9bcd468 sp=0xa9bcd3f4
[DAWN2] 
[DAWN2] E/Go      : runtime.adjustframe(0xa9bcd628, 0xa9bcd698, 0xa9bcd501)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/stack.go:644 +0x1b8 fp=0xa9bcd4d0 sp=0xa9bcd468
[DAWN2] 
[DAWN2] E/Go      : runtime.gentraceback(0xdda40200, 0xbdbf9df8, 0xddb2b2bc, 0xbdff5ad0, 0x0, 0x0, 0x7fffffff, 0xde6fcea8, 0xa9bcd698, 0x0, ...)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/traceback.go:369 +0xdb0 fp=0xa9bcd650 sp=0xa9bcd4d0
[DAWN2] 
[DAWN2] E/Go      : runtime.copystack(0xbdff5ad0, 0x1000)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/stack.go:759 +0x15c fp=0xa9bcd788 sp=0xa9bcd650
[DAWN2] 
[DAWN2] E/Go      : runtime.shrinkstack(0xbdff5ad0)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/stack.go:1026 +0x150 fp=0xa9bcd7a0 sp=0xa9bcd788
[DAWN2] 
[DAWN2] E/Go      : runtime.markroot(0xc3)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/mgcmark.go:155 +0x2f4 fp=0xa9bcd7f4 sp=0xa9bcd7a0
[DAWN2] 
[DAWN2] E/Go      : runtime.gcDrain(0xa9bcd838, 0x0)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/mgcmark.go:812 +0x318 fp=0xa9bcd824 sp=0xa9bcd7f4
[DAWN2] 
[DAWN2] E/Go      : runtime.gchelper()
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/mgc.go:1802 +0x84 fp=0xa9bcd854 sp=0xa9bcd824
[DAWN2] 
[DAWN2] E/Go      : runtime.stopm()
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/proc.go:1538 +0x148 fp=0xa9bcd864 sp=0xa9bcd854
[DAWN2] 
[DAWN2] E/Go      : runtime.startlockedm(0xbd86da00)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/proc.go:1712 +0xcc fp=0xa9bcd874 sp=0xa9bcd864
[DAWN2] 
[DAWN2] E/Go      : runtime.schedule()
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/proc.go:2085 +0x2dc fp=0xa9bcd890 sp=0xa9bcd874
[DAWN2] 
[DAWN2] E/Go      : runtime.exitsyscall0(0xbdd7d2b0)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/proc.go:2585 +0x198 fp=0xa9bcd8a8 sp=0xa9bcd890
[DAWN2] 
[DAWN2] E/Go      : runtime.mcall(0xbd662000)
[DAWN2] 
[DAWN2] E/Go      :     /usr/local/google/home/toddw/vroot/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/asm_arm.s:183 +0x60 fp=0xa9bcd8b0 sp=0xa9bcd8a8
[DAWN2] 
```

Next we try to restart the todos app, but every time we restart it, it complains about the database being corrupt.  Note that we've also seen the above crash without database corruption.  I've only seen the database corruption once.  Here's the logs:

```
[DAWN2] I/vlog    : I0609 01:52:58.228587   13161 service.go:159] Using persisted permissions: {"Admin":{"In":["dev.v.io:o:608941808256-43vtfndets79kf5hac8ieujto8837660.apps.googleusercontent.com:dawn.vanadium@gmail.com","dev.v.io:u:alexfandrianto@google.com"],"NotIn":null},"Read":{"In":["dev.v.io:o:608941808256-43vtfndets79kf5hac8ieujto8837660.apps.googleusercontent.com:dawn.vanadium@gmail.com","dev.v.io:u:alexfandrianto@google.com"],"NotIn":null},"Resolve":{"In":["..."],"NotIn":null},"Write":{"In":["dev.v.io:o:608941808256-43vtfndets79kf5hac8ieujto8837660.apps.googleusercontent.com:dawn.vanadium@gmail.com","dev.v.io:u:alexfandrianto@google.com"],"NotIn":null}}
[DAWN2] 
[DAWN2] E/vlog    : E0609 01:52:58.286646   13161 funcs.go:94] leveldb /data/user/0/io.v.todos.syncbase/files/syncbase/apps/dev_v_io_o_608941808256-43vtfnde-429e99929207196fd05e27fa2580db95702112eb7865b82f80adf0906e213a82/dbs/db-7bdc25d1694ef984782a16f6f1710c1c6bc83ba7a131b515baf532bea021d011-04e7432bc910edcb20f8f444c107588ec0dc55b5c73c37aa1d01dfd00202e64d/leveldb is corrupt.  Moving aside. gojni: Internal error: Corruption: bad record length
[DAWN2] 
[DAWN2] W/vlog    : E0609 01:52:58.286646   13161 funcs.go:94] leveldb /data/user/0/io.v.todos.syncbase/files/syncbase/apps/dev_v_io_o_608941808256-43vtfnde-429e99929207196fd05e27fa2580db95702112eb7865b82f80adf0906e213a82/dbs/db-7bdc25d1694ef984782a16f6f1710c1c6bc83ba7a131b515baf532bea021d011-04e7432bc910edcb20f8f444c107588ec0dc55b5c73c37aa1d01dfd00202e64d/leveldb is corrupt.  Moving aside. gojni: Internal error: Corruption: bad record length
[DAWN2] 
[DAWN2] I/vlog    : E0609 01:52:58.286646   13161 funcs.go:94] leveldb /data/user/0/io.v.todos.syncbase/files/syncbase/apps/dev_v_io_o_608941808256-43vtfnde-429e99929207196fd05e27fa2580db95702112eb7865b82f80adf0906e213a82/dbs/db-7bdc25d1694ef984782a16f6f1710c1c6bc83ba7a131b515baf532bea021d011-04e7432bc910edcb20f8f444c107588ec0dc55b5c73c37aa1d01dfd00202e64d/leveldb is corrupt.  Moving aside. gojni: Internal error: Corruption: bad record length
[DAWN2] 
[DAWN2] E/STDERR  : E0609 01:52:58.286646   13161 funcs.go:94] leveldb /data/user/0/io.v.todos.syncbase/files/syncbase/apps/dev_v_io_o_608941808256-43vtfnde-429e99929207196fd05e27fa2580db95702112eb7865b82f80adf0906e213a82/dbs/db-7bdc25d1694ef984782a16f6f1710c1c6bc83ba7a131b515baf532bea021d011-04e7432bc910edcb20f8f444c107588ec0dc55b5c73c37aa1d01dfd00202e64d/leveldb is corrupt.  Moving aside. gojni: Internal error: Corruption: bad record length
[DAWN2] 
[DAWN2] E/vlog    : E0609 01:52:58.291467   13161 service.go:258] database dev.v.io:o:608941808256-43vtfndets79kf5hac8ieujto8837660.apps.googleusercontent.com,db is corrupt, deleting the reference to it
[DAWN2] 
[DAWN2] W/vlog    : E0609 01:52:58.291467   13161 service.go:258] database dev.v.io:o:608941808256-43vtfndets79kf5hac8ieujto8837660.apps.googleusercontent.com,db is corrupt, deleting the reference to it
[DAWN2] 
[DAWN2] E/STDERR  : E0609 01:52:58.291467   13161 service.go:258] database dev.v.io:o:608941808256-43vtfndets79kf5hac8ieujto8837660.apps.googleusercontent.com,db is corrupt, deleting the reference to it
[DAWN2] 
[DAWN2] I/vlog    : E0609 01:52:58.291467   13161 service.go:258] database dev.v.io:o:608941808256-43vtfndets79kf5hac8ieujto8837660.apps.googleusercontent.com,db is corrupt, deleting the reference to it
[DAWN2] 
[DAWN2] E/PersistenceInitializer: io.v.impl.google.services.syncbase.SyncbaseServer$StartException: gojni: Internal error: gojni: database corrupt, moved to '/data/user/0/io.v.todos.syncbase/files/syncbase/apps/dev_v_io_o_608941808256-43vtfnde-429e99929207196fd05e27fa2580db95702112eb7865b82f80adf0906e213a82/dbs/db-7bdc25d1694ef984782a16f6f1710c1c6bc83ba7a131b515baf532bea021d011-04e7432bc910edcb20f8f444c107588ec0dc55b5c73c37aa1d01dfd00202e64d/leveldb.corrupt.2016-06-09T01:52:58Z'; client must create a new database
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.impl.google.services.syncbase.SyncbaseServer.withNewServer(SyncbaseServer.java:34)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.todos.persistence.syncbase.SyncbasePersistence.startSyncbaseServer(SyncbasePersistence.java:184)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.todos.persistence.syncbase.SyncbasePersistence.ensureSyncbaseStarted(SyncbasePersistence.java:253)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.todos.persistence.syncbase.SyncbasePersistence.<init>(SyncbasePersistence.java:566)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.todos.persistence.syncbase.SyncbaseMain.<init>(SyncbaseMain.java:61)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.todos.persistence.PersistenceFactory.getMainPersistence(PersistenceFactory.java:33)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.todos.MainActivity$3.initPersistence(MainActivity.java:82)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.todos.MainActivity$3.initPersistence(MainActivity.java:79)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.todos.PersistenceInitializer$1.doInBackground(PersistenceInitializer.java:59)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at io.v.todos.PersistenceInitializer$1.doInBackground(PersistenceInitializer.java:55)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at android.os.AsyncTask$2.call(AsyncTask.java:295)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
[DAWN2] 
[DAWN2] E/PersistenceInitializer:   at java.lang.Thread.run(Thread.java:818)
[DAWN2] 
```

I tried to pull the actual corrupt database, but didn't manage to get it in time.  FYI "adb pull" won't work, since you won't have the right permissions.  Instead you need to do something like this:

```
adb shell
run-as io.v.todos.syncbase
...
```

More info here:
http://stackoverflow.com/questions/15558353/how-can-one-pull-the-private-data-of-ones-own-android-app

**Comment by asadovsky** [comment]
Regarding the app crashing with "invalid stack pointer": do all such crashes give the same stack trace? Alex has mentioned that this happens on occasion, though according to him it primarily happens on tablets, and only on pre-Marshmallow devices. Are you seeing something different? We haven't investigated this in depth because (a) it's hard to reproduce, and (b) the culprit is likely JNI, and our entire JNI implementation is about to change.

Regarding the LevelDB corruption: that's concerning. Do we have any idea what the app might've been doing at the time when it crashed? Presumably the LevelDB is only corrupt on one of the devices?

The good news is that our code that talks to LevelDB is pretty well contained, so we can try to comb through it: https://github.com/vanadium/go.ref/tree/master/services/syncbase/store/leveldb
(Sergey wrote most of this code, though others have made minor changes more recently.)

May also be worth checking if any of these reported LevelDB bugs seem relevant - e.g. is "app crash" similar to "power loss":
https://github.com/google/leveldb/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Abug+corrupt

Finally, regarding "every time we restart it, it complains about the database being corrupt": that's unexpected. IIRC, what's supposed to happen is the database gets moved aside after being detected as corrupt, and subsequently will appear to not exist.
https://github.com/vanadium/go.v23/blob/master/syncbase/featuretests/restartability_v23_test.go#L436
https://github.com/vanadium/go.ref/blob/b7beb515da63b38023bf43c39eb97e4bff576aab/services/syncbase/store/util/util.go#L47

It sounds like you are seeing different behavior - namely, that on every subsequent launch of the app, the database is reported as corrupt? If so, we need to investigate to understand why this behavior is different from what's covered in our tests.

**Comment by tatatodd** [comment]
@mattr-google @suharshs @razvanm 

WRT the "invalid stack pointer" crashes, I've seen it at least 2 times on Nexus 5x running M.  Matt's also seen it, but I dunno what device/OS he was running.  Both times I saw the crash it was in the Go GC code.  I completely agree we should punt on it, since all of our JNI will soon change; I should have mentioned that.

Attached is a full dump of the stacktraces when the crash occurred. I'm not sure what to look for syncbase-wise, but maybe this'll help narrow down what happened:
[crash.txt](https://github.com/vanadium/issues/files/306387/crash.txt)

Yes, the DB corruption was only on one of the devices; other DBs that were synced were not affected.

WRT "every time we restart it", you're right, I was mistaken.  What actually happened was that I got the "invalid stack pointer" crash, then I got the "database corrupt" error, which gives the dreaded "unable to initialize persistence" toast from the app.

Then I tried to start the app two more times, and saw "unable to initialize persistence" both times.  I'd assumed it was the same problem.  But looking at the logs, the failures were actually this both times:

```
E/PersistenceInitializer: io.v.impl.google.services.syncbase.SyncbaseServer$StartException: gojni: Internal error: IO error: lock /data/user/0/io.v.todos.syncbase/files/syncbase/leveldb/LOCK: already held by process
E/PersistenceInitializer:   at io.v.impl.google.services.syncbase.SyncbaseServer.withNewServer(SyncbaseServer.java:34)
E/PersistenceInitializer:   at io.v.todos.persistence.syncbase.SyncbasePersistence.startSyncbaseServer(SyncbasePersistence.java:184)
E/PersistenceInitializer:   at io.v.todos.persistence.syncbase.SyncbasePersistence.ensureSyncbaseStarted(SyncbasePersistence.java:253)
E/PersistenceInitializer:   at io.v.todos.persistence.syncbase.SyncbasePersistence.<init>(SyncbasePersistence.java:566)
E/PersistenceInitializer:   at io.v.todos.persistence.syncbase.SyncbaseMain.<init>(SyncbaseMain.java:61)
E/PersistenceInitializer:   at io.v.todos.persistence.PersistenceFactory.getMainPersistence(PersistenceFactory.java:33)
E/PersistenceInitializer:   at io.v.todos.MainActivity$3.initPersistence(MainActivity.java:82)
E/PersistenceInitializer:   at io.v.todos.MainActivity$3.initPersistence(MainActivity.java:79)
E/PersistenceInitializer:   at io.v.todos.PersistenceInitializer$1.doInBackground(PersistenceInitializer.java:59)
E/PersistenceInitializer:   at io.v.todos.PersistenceInitializer$1.doInBackground(PersistenceInitializer.java:55)
E/PersistenceInitializer:   at android.os.AsyncTask$2.call(AsyncTask.java:295)
E/PersistenceInitializer:   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/PersistenceInitializer:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/PersistenceInitializer:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/PersistenceInitializer:   at java.lang.Thread.run(Thread.java:818)
```

After this occurred, I gave up and cleared app data, which let me restart the app, and continued testing other stuff.  You might want to look into this lockfile, since effectively it means the app can't be restarted.

**Comment by razvanm** [comment]
I believe the "lock ... already held by process" comes from `DBImpl::Recover` ([db_impl.cc:282](https://github.com/vanadium/third_party/blob/2c66f153a49a12a64a3cf5e6bb8056858630a0c9/csrc/leveldb/db/db_impl.cc#L282)).

There are some reports of this type of error when using LevelDB (example: https://github.com/Level/levelup/issues/211). We should probably take a closer look at what happen when we open a table.

**Comment by razvanm** [comment]
Looking some more: the `DBImpl::Recover` is called during open and it's responsible for creating the database if it doesn't exist ([db_impl.cc:1452](https://github.com/vanadium/third_party/blob/2c66f153a49a12a64a3cf5e6bb8056858630a0c9/csrc/leveldb/db/db_impl.cc#L1452)). I'm haven't look at how the `LOCK` files are used. One possibility is that the file needs to be manually removed to indicate that the user of the database is aware that the LevelDB crashed.

**Comment by razvanm** [comment]
My hypothesis was wrong: the `LOCK` doesn't need to be removed. The "lock ... already held by process" really indicates that the _current_ process has already locked the file ([env_posix.cc:422](https://github.com/vanadium/third_party/blob/2c66f153a49a12a64a3cf5e6bb8056858630a0c9/csrc/leveldb/util/env_posix.cc#L422)).
