### ISSUE TITLE
Random Callback Crashes on Android

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1368]
The error is: `fatal error: bad pointer in write barrier` [full trace](https://paste.googleplex.com/6711436122259456)

This crash happens randomly when a callback (watch, invite, peer scan, etc.) is triggered. However, it doesn't seem to affect iOS so far. You can reproduce this by spamming changes, which makes the watch callback fire a lot.

Here's an example of just the first goroutine.

```
06-24 15:23:50.626 9372-0/io.v.todos.syncbase2 E/Go: fatal error: bad pointer in write barrier
06-24 15:23:50.891 9372-0/io.v.todos.syncbase2 E/Go: runtime stack:
06-24 15:23:50.891 9372-0/io.v.todos.syncbase2 E/Go: runtime.throw(0x9e215478, 0x1c)
06-24 15:23:50.891 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/panic.go:530 +0x80
06-24 15:23:50.891 9372-0/io.v.todos.syncbase2 E/Go: runtime.writebarrierptr_nostore.func1()
06-24 15:23:50.892 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/mbarrier.go:157 +0x28
06-24 15:23:50.892 9372-0/io.v.todos.syncbase2 E/Go: runtime.systemstack(0x4f291400)
06-24 15:23:50.892 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/asm_arm.s:247 +0x8c
06-24 15:23:50.892 9372-0/io.v.todos.syncbase2 E/Go: runtime.mstart()
06-24 15:23:50.893 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/proc.go:1048
06-24 15:23:50.893 9372-0/io.v.todos.syncbase2 E/Go: goroutine 245 [running]:
06-24 15:23:50.895 9372-0/io.v.todos.syncbase2 E/Go: runtime.systemstack_switch()
06-24 15:23:50.895 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/asm_arm.s:192 +0x4 fp=0x4f899e24 sp=0x4f899e20
06-24 15:23:50.895 9372-0/io.v.todos.syncbase2 E/Go: runtime.writebarrierptr_nostore(0x4f776860, 0x1)
06-24 15:23:50.895 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/mbarrier.go:157 +0x88 fp=0x4f899e30 sp=0x4f899e24
06-24 15:23:50.895 9372-0/io.v.todos.syncbase2 E/Go: runtime.heapBitsBulkBarrier(0x4f776860, 0x8)
06-24 15:23:50.895 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/mbitmap.go:437 +0x240 fp=0x4f899e7c sp=0x4f899e30
06-24 15:23:50.895 9372-0/io.v.todos.syncbase2 E/Go: runtime.typedmemmove(0x9e0d0f80, 0x4f776860, 0x4f899efc)
06-24 15:23:50.895 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/mbarrier.go:197 +0x98 fp=0x4f899e94 sp=0x4f899e7c
06-24 15:23:50.895 9372-0/io.v.todos.syncbase2 E/Go: runtime.convT2E(0x9e0d0f80, 0x4f899efc, 0x4f776860, 0x0, 0x0)
06-24 15:23:50.896 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/iface.go:144 +0xc8 fp=0x4f899ea8 sp=0x4f899e94
06-24 15:23:50.896 9372-0/io.v.todos.syncbase2 E/Go: main.v23_syncbase_DbSyncgroupInvitesNewScan.func1(0x4f603580, 0x1, 0x9de4ed88)
06-24 15:23:50.896 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/services/syncbase/bridge/cgo/impl.go:771 +0xd8 fp=0x4f899fcc sp=0x4f899ea8
06-24 15:23:50.896 9372-0/io.v.todos.syncbase2 E/Go: runtime.goexit()
06-24 15:23:50.896 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/.jiri_root/profiles/v23/go/shared/1.6/src/runtime/asm_arm.s:990 +0x4 fp=0x4f899fcc sp=0x4f899fcc
06-24 15:23:50.896 9372-0/io.v.todos.syncbase2 E/Go: created by main.v23_syncbase_DbSyncgroupInvitesNewScan
06-24 15:23:50.896 9372-0/io.v.todos.syncbase2 E/Go:    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/services/syncbase/bridge/cgo/impl.go:773 +0x168
```

@ultrasaurus @azinman

**Comment by afandria** [comment]
This has been fixed in v.io/c/23681
