### ISSUE TITLE
syncslides java rpc - buggy endpoint caching behavior?

### ISSUE THREAD

**Issue by monopole** [vanadium/issues#812]
The current approach to discovery in syncslides is:
- Person presenting a deck mounts a service with a name like livedeck/foo that has critical info about the deck.
- Other folks poll the MT, and call get on any new service they see to Get deck info.

Because of corner-cutting design (the intent is to junk this approach to discovery shortly), the service unmounts and is recreated/remounted with every phone rotation (or other user actions).

The following consistently fails
- client process makes a successful Get rpc.
- presenter phone rotates
- client process calls ParticipantClientFactory.getParticipantClient("livedeck/foo") to get a new v23 'client'
- Subsequent Get rpc fails with stack trace below
- the next Get in the polling hangs solid (the client is unresponsive, and has to be killed).

This problem goes away if one calls  V.getNamespace(mBaseContext).flushCacheEntry(mBaseContext, livedeck/foo)
before calling getParticipantClient.

 https://vanadium-review.googlesource.com/#/c/16869 is compiled into the app.

stack trace:

```
 io.v.v23.verror.VException: gojni:<rpc.Client>"liveDeck/2".Get: ended before version byte received : failed to decode response: gojni: ended before version byte received : EOF
10-21 09:50:45.432 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.verror.VExceptionVdlConverter.nativeFromVdlValue(VExceptionVdlConverter.java:70)
10-21 09:50:45.432 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.verror.VExceptionVdlConverter.nativeFromVdlValue(VExceptionVdlConverter.java:22)
10-21 09:50:45.432 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.vom.BinaryDecoder.readValue(BinaryDecoder.java:190)
10-21 09:50:45.432 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.vom.BinaryDecoder.readValueMessage(BinaryDecoder.java:118)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.vom.BinaryDecoder.decodeValue(BinaryDecoder.java:85)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.vom.VomUtil.decode(VomUtil.java:110)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.impl.google.rpc.ClientCallImpl.nativeFinish(Native Method)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.impl.google.rpc.ClientCallImpl.finish(ClientCallImpl.java:40)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System
10-21 09:50:45.431 27199-28276/io.v.android.apps.syncslides D/ParticipantPeer: RPC failed, leaving current deck in place.
10-21 09:50:45.431 27199-28276/io.v.android.apps.syncslides W/System.err: io.v.v23.verror.VException: gojni:<rpc.Client>"liveDeck/2".Get: ended before version byte received : failed to decode response: gojni: ended before version byte received : EOF
10-21 09:50:45.432 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.verror.VExceptionVdlConverter.nativeFromVdlValue(VExceptionVdlConverter.java:70)
10-21 09:50:45.432 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.verror.VExceptionVdlConverter.nativeFromVdlValue(VExceptionVdlConverter.java:22)
10-21 09:50:45.432 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.vom.BinaryDecoder.readValue(BinaryDecoder.java:190)
10-21 09:50:45.432 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.vom.BinaryDecoder.readValueMessage(BinaryDecoder.java:118)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.vom.BinaryDecoder.decodeValue(BinaryDecoder.java:85)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.v23.vom.VomUtil.decode(VomUtil.java:110)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.impl.google.rpc.ClientCallImpl.nativeFinish(Native Method)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.impl.google.rpc.ClientCallImpl.finish(ClientCallImpl.java:40)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.android.apps.syncslides.discovery.ParticipantClientImpl.get(ParticipantClientImpl.java:65)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.android.apps.syncslides.discovery.ParticipantClientImpl.get(ParticipantClientImpl.java:44)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.android.apps.syncslides.discovery.ParticipantPeer.refreshData(ParticipantPeer.java:127)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.android.apps.syncslides.discovery.Moderator.process(Moderator.java:97)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at io.v.android.apps.syncslides.discovery.Moderator.run(Moderator.java:63)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:279)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:152)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-21 09:50:45.433 27199-28276/io.v.android.apps.syncslides W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by monopole** [comment]
@sjamesr

**Comment by monopole** [comment]
@kenashcraft 

Waiting for an lgtm on https://vanadium-review.googlesource.com/#/c/16881, to make it easier for others to repro this.

We can always delete the line that flushes later.

**Comment by kenashcraft** [comment]
@spetrovic77

**Comment by ghost** [comment]
Hello,

For non-streaming RPCs we should be able to retry internally and avoid the error on the second call, for streaming RPCs, sadly, the user will have to do this retrying for us.

The hang is certainly a bug, if you can repro this please kill the hung client with sigabrt to get a go stack trace.  It would be most helpful to see how it's hung.  It is likely that we have a mishandled error case as the logic around handling errors is complex.

**Comment by ghost** [comment]
This was fixed.
