### ISSUE TITLE
Vanadium chat is down

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#902]
@aghassemi Can you take a look at this since Nick is out?  Do you have any idea what the issue is?

https://chat.staging.v.io/#  doesn't connect which results in a jenkins failure:

https://veyron.corp.google.com/jenkins/job/vanadium-chat-web-ui-test/

Session ID: a8ddca0009455d0abf6d3b24cbc52ff1
    at org.junit.Assert.fail(Assert.java:88)
    at io.v.webdriver.chat.MainPage.checkUserIsMember(MainPage.java:146)
    at io.v.webdriver.chat.MainPage.validatePage(MainPage.java:131)
    at io.v.webdriver.chat.ChatUITest.testInitProcess(ChatUITest.java:52)

Results :

Failed tests: 
  ChatUITest.testInitProcess:52 org.openqa.selenium.TimeoutException: Timed out after 10 seconds waiting for io.v.webdriver.chat.MainPage$CheckMember@1283bb96

**Comment by aghassemi** [comment]
Will do

**Comment by ghost** [comment]
This has also broken the www-tutorials-js test:
https://veyron.corp.google.com/jenkins/job/vanadium-www-tutorials-js-web/512/console

We believe this is because Suharshs published the new proxy today that works with the new RPC system.  The published extension doesn't know how to deal with two proxies.  The fix should be to simply build a new extension, but when @aghassemi tries the extension just crashes.

This is surprising given that the javascript integration tests pass with a freshly built extension.  Ali is still investigating.
