### ISSUE TITLE
Differentiate V.init exceptions

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#934]
Right now, if you pass an invalid option like a malformed VMODULE setting (e.g. "42") into V.init, you get a RuntimeException caused by an UnknownException. It might be nice to differentiate these (which for example an app might recover from by V.init-ing with default options instead) from other failures.

Or it might not be worthwhile; submitting issue to track and get feedback.

**Comment by AsturaPhoenix** [comment]
Example trace:

```
java.lang.RuntimeException: Couldn't initialize Android
    at io.v.android.v23.V.initAndroid(V.java:44)
    at io.v.android.v23.V.init(V.java:75)
    at io.v.baku.toolkit.VAndroidContextTrait.vinit(VAndroidContextTrait.java:79)
    at io.v.baku.toolkit.VAndroidContextTrait.<init>(VAndroidContextTrait.java:108)
    at io.v.baku.toolkit.VAndroidContextTrait.withDefaults(VAndroidContextTrait.java:134)
    at io.v.baku.toolkit.VActivity.createVActivityTrait(VActivity.java:23)
    at io.v.baku.toolkit.VActivity.onCreate(VActivity.java:29)
    at io.v.baku.toolkit.BakuActivity.onCreate(BakuActivity.java:31)
    at io.v.baku.hellobaku.HelloActivity.onCreate(HelloActivity.java:17)
    at android.app.Activity.performCreate(Activity.java:6500)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218)
    at android.app.ActivityThread.access$1000(ActivityThread.java:198)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6837)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
 Caused by: io.v.v23.verror.UnknownException: v.io/v23/verror.Unknown:   syntax error: expect comma-separated list of filename=N
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
    at io.v.v23.verror.VExceptionVdlConverter.nativeFromVdlValue(VExceptionVdlConverter.java:85)
    at io.v.v23.vom.BinaryDecoder.readValue(BinaryDecoder.java:190)
    at io.v.v23.vom.BinaryDecoder.readValueMessage(BinaryDecoder.java:118)
    at io.v.v23.vom.BinaryDecoder.decodeValue(BinaryDecoder.java:85)
    at io.v.v23.vom.VomUtil.decode(VomUtil.java:110)
    at io.v.android.v23.V.nativeInitAndroid(Native Method)
    at io.v.android.v23.V.initAndroid(V.java:42)
    at io.v.android.v23.V.init(V.java:75) 
    at io.v.baku.toolkit.VAndroidContextTrait.vinit(VAndroidContextTrait.java:79) 
    at io.v.baku.toolkit.VAndroidContextTrait.<init>(VAndroidContextTrait.java:108) 
    at io.v.baku.toolkit.VAndroidContextTrait.withDefaults(VAndroidContextTrait.java:134) 
    at io.v.baku.toolkit.VActivity.createVActivityTrait(VActivity.java:23) 
    at io.v.baku.toolkit.VActivity.onCreate(VActivity.java:29) 
    at io.v.baku.toolkit.BakuActivity.onCreate(BakuActivity.java:31) 
    at io.v.baku.hellobaku.HelloActivity.onCreate(HelloActivity.java:17) 
    at android.app.Activity.performCreate(Activity.java:6500) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218) 
    at android.app.ActivityThread.access$1000(ActivityThread.java:198) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:145) 
    at android.app.ActivityThread.main(ActivityThread.java:6837) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
```
