### ISSUE TITLE
Java test flaky

### ISSUE THREAD

**Issue by suharshs** [vanadium/issues#974]
See the full stack trace here:
https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-java-test/16643/consoleFull

Here is the relevant snippet from the stack trace.

```
 panic: runtime error: index out of range
01:19:13 
01:19:13 goroutine 3077 [running]:
01:19:13 v.io/v23/vom.(*encoder).StartField(0xc821ad79c0, 0x7f222b890988, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
01:19:13    /home/veyron/workspace/pt/root/release/go/src/v.io/v23/vom/encoder.go:673 +0x571
01:19:13 v.io/v23/vdl.FromReflect(0x7f222840b938, 0xc821ad79c0, 0x7f222b786220, 0xc82086c9e8, 0x59, 0x0, 0x0)
01:19:13    /home/veyron/workspace/pt/root/release/go/src/v.io/v23/vdl/target.go:357 +0x24e5
01:19:13 v.io/v23/vdl.FromReflect(0x7f222840b938, 0xc821ad79c0, 0x7f222b786100, 0xc82086c9e0, 0x59, 0x0, 0x0)
01:19:13    /home/veyron/workspace/pt/root/release/go/src/v.io/v23/vdl/target.go:372 +0x294a
01:19:13 v.io/v23/vdl.FromReflect(0x7f222840b938, 0xc821ad79c0, 0x7f222b7c81c0, 0xc82086c9c0, 0x59, 0x0, 0x0)
01:19:13    /home/veyron/workspace/pt/root/release/go/src/v.io/v23/vdl/target.go:372 +0x294a
01:19:13 v.io/v23/vom.(*Encoder).Encode(0xc821ad79c0, 0x7f222b7c81c0, 0xc82086c9c0, 0x0, 0x0)
01:19:13    /home/veyron/workspace/pt/root/release/go/src/v.io/v23/vom/encoder.go:167 +0x337
01:19:13 v.io/x/ref/runtime/internal/rpc.(*xflowServer).Send(0xc8217b6c30, 0x7f222b862340, 0xc820902b60, 0x0, 0x0)
01:19:13    /home/veyron/workspace/pt/root/release/go/src/v.io/x/ref/runtime/internal/rpc/xserver.go:775 +0x10b
01:19:13 v.io/x/jni/impl/google/rpc.Java_io_v_impl_google_rpc_StreamImpl_nativeSend.func1(0x0, 0x0, 0x0)
01:19:13    /home/veyron/workspace/pt/root/release/go/src/v.io/x/jni/impl/google/rpc/jni.go:320 +0x12b
01:19:13 v.io/x/jni/util.DoAsyncCall.func1(0xc8208d7a70, 0x7f21f4012258)
01:19:13    /home/veyron/workspace/pt/root/release/go/src/v.io/x/jni/util/call.go:318 +0x23
01:19:13 created by v.io/x/jni/util.DoAsyncCall
01:19:13    /home/veyron/workspace/pt/root/release/go/src/v.io/x/jni/util/call.go:334 +0x59
01:19:13 
```

**Comment by suharshs** [comment]
obsolete
